### ISSUE TITLE
when a user deregisters, the DM room name gets encrypted

### ISSUE THREAD

**Issue by ergunirem** [42-jkoers/ft_transcendence#146]
I might add this as an issue but I realized that when I deregister one side of the DM, the room name changes to this but I really think this is a minor issue not a priority
![Screenshot 2022-06-27 at 18 01 42](https://user-images.githubusercontent.com/57744064/175972600-3b6aba3d-1bdc-4dc0-b061-aa692fc1c5d4.png)

_Originally posted by @ergunirem in https://github.com/42-jkoers/ft_transcendence/issues/138#issuecomment-1167468761_

**Comment by Mollie-S** [comment]
yes, we're aware there might be the problem with it. this issue is linked to #137

**Comment by Mollie-S** [comment]
I'll keep it open. Will fix later

**Comment by Mollie-S** [comment]
Account deleting functionality is removed in #164
