### ISSUE TITLE
what is best practice while query building?

### ISSUE THREAD

**Issue by ergunirem** [42-jkoers/ft_transcendence#46]
Using the injected repository i.e. const query = this.messageRepository.createQueryBuilder();
OR
using getRepository function i.e. const query = await getRepository(RoomEntity);

**Comment by Mollie-S** [comment]
You can use any of them.
[This] (https://orkhan.gitbook.io/typeorm/docs/select-query-builder) says there are 3 ways to create QueryBuikder in Typeorm.
