### ISSUE TITLE
absence of upload folder causing compile error

### ISSUE THREAD

**Issue by ergunirem** [42-jkoers/ft_transcendence#69]
When I clone from the main and try to compile frontend, I get this error. I realise there is no 'upload folder' 

 ERROR  Failed to compile with 1 error                                                                                                                                                                         12:20:24 PM

 error  in ./src/components/UpdateUserInfo.vue?vue&type=script&setup=true&lang=ts

Module not found: Error: Can't resolve `**'../../../upload'**` in '/Users/icikrikc/Desktop/current/frontend/src/components'

ERROR in ./src/components/UpdateUserInfo.vue?vue&type=script&setup=true&lang=ts (./node_modules/ts-loader/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/UpdateUserInfo.vue?vue&type=script&setup=true&lang=ts) 40:27-62
Module not found: Error: Can't resolve '../../../upload' in '/Users/icikrikc/Desktop/current/frontend/src/components'
 @ ./src/components/UpdateUserInfo.vue?vue&type=script&setup=true&lang=ts 1:0-210 1:0-210 1:211-410 1:211-410
 @ ./src/components/UpdateUserInfo.vue 2:0-76 3:0-71 3:0-71 8:49-55
 @ ./node_modules/ts-loader/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/RegisterView.vue?vue&type=script&setup=true&lang=ts 2:0-61 14:77-91
 @ ./src/views/RegisterView.vue?vue&type=script&setup=true&lang=ts 1:0-208 1:0-208 1:209-406 1:209-406
 @ ./src/views/RegisterView.vue 2:0-74 3:0-69 3:0-69 6:49-55
 @ ./src/router/index.ts 4:0-52 65:19-31
 @ ./src/main.ts 3:0-30 12:8-14

webpack compiled with 1 error

**Comment by aprilmayjune135** [comment]
> I think it is because we have upload/* in gitignore file. We have to push an empty upload folder first. 

I created the directory in the run.sh file, but maybe I can move it to the Makefile
